version: '3.3'
services:
  user-info-api:
    image: repo.roham.co.ir/repository/docker-registry/cap-gem:BUILD_NUMBER
    container_name: user-info-api
    ports:
      - 9854:8080
      - 9855:8000
    extra_hosts:
      - "localhost:8080"
    tty: true
    build: .
    restart: always
    networks:
      - cap-gem
networks:
  roham-app:
    name: cap-gem_network
    external: true