version: '3.3'
services:
  cap-gem-api:
    image: repo.capgem.com/repository/docker-registry/cap-gem:BUILD_NUMBER
    container_name: cap-gem-api
    ports:
      - 9854:8080
      - 9855:8000
    extra_hosts:
      - "localhost:8080"
    tty: true
    build: .
    restart: always
    networks:
      - cap-gem
networks:
  cap-gem:
    name: cap-gem_network
    external: true