INSERT INTO CUSTOMER(ID, NAME, SURNAME, ACCOUNT_FK)
VALUES (1, 'Mahsa', 'Saeedi', null);
INSERT INTO CUSTOMER(ID, NAME, SURNAME, ACCOUNT_FK)
VALUES (2, 'Behnaz', 'Tehrani', null);
INSERT INTO CUSTOMER(ID, NAME, SURNAME, ACCOUNT_FK)
VALUES (3, 'Elham', 'Heydari', null);