INSERT INTO ACCOUNT(ID, ACCOUNT_NUMBER, BALANCE, ACCOUNT_TYPE)
VALUES (1, 14526987, 123650, 1);
INSERT INTO ACCOUNT(ID, ACCOUNT_NUMBER, BALANCE, ACCOUNT_TYPE)
VALUES (2, 12345678, 50050, 2);
INSERT INTO ACCOUNT(ID, ACCOUNT_NUMBER, BALANCE, ACCOUNT_TYPE)
VALUES (3, 9876543, 986500, 3);
INSERT INTO CUSTOMER(ID, NAME, SURNAME, ACCOUNT_ID)
VALUES (1, 'Mahsa', 'Saeedi', 1);
INSERT INTO CUSTOMER(ID, NAME, SURNAME, ACCOUNT_ID)
VALUES (2, 'Behnaz', 'Tehrani', 2);
INSERT INTO CUSTOMER(ID, NAME, SURNAME, ACCOUNT_ID)
VALUES (3, 'Elham', 'Heydari', 3);